eureka:
  client:
    enabled: false

security:
  basic:
    enabled: false
  management:
    security:
      enabled: false

api:
  campaignapi:
    path: /v1/campaign

feign:
  campaign:
    name: CampaignAPI
    url: http://localhost:8081
    
logging.level.com.bpedroso.challenge.gateways.feign.ProductClient: FULL
