eureka:
  client:
    enabled: false

security:
  basic:
    enabled: false
  management:
    security:
      enabled: false

feign:
  campaignapi:
    name: CampaignAPI
    url: http://localhost:8081
    endpoints:
      campaign: /v1/campaign
      user: /v1/user
  
  
logging.level.com.bpedroso.challenge.gateways.feign.CampaignClient: FULL
logging.level.com.bpedroso.challenge.gateways.feign.UserClient: FULL

